#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-rsync

VERSION=2.6.9
ARCH=${ARCH:-i386}
BUILD=1_slack9.0

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
rm -rf $PKG
mkdir -p $PKG

# Explode the package framework:
cd $PKG
explodepkg $CWD/_rsync.tar.gz

cd $TMP
rm -rf rsync-$VERSION
tar xzvf $CWD/rsync-$VERSION.tar.gz
cd rsync-$VERSION

zcat $CWD/munge-symlinks-2.6.9.diff.gz | patch -p1 || exit 1
zcat $CWD/rsync-2.6.9-CVE-2007-4091.diff.gz | patch -p1 || exit 1

chown -R root:root .
find . -perm 666 -exec chmod 644 {} \;
find . -perm 664 -exec chmod 644 {} \;
find . -perm 600 -exec chmod 644 {} \;
find . -perm 444 -exec chmod 644 {} \;
find . -perm 400 -exec chmod 644 {} \;
find . -perm 440 -exec chmod 644 {} \;
find . -perm 777 -exec chmod 755 {} \;
find . -perm 775 -exec chmod 755 {} \;
find . -perm 511 -exec chmod 755 {} \;
find . -perm 711 -exec chmod 755 {} \;
find . -perm 555 -exec chmod 755 {} \;

CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr
make -j4 || exit
mkdir -p $PKG/usr/bin
cat rsync > $PKG/usr/bin/rsync
chmod 755 $PKG/usr/bin/rsync
mkdir -p $PKG/usr/man/man1
cat rsync.1 | gzip -9c > $PKG/usr/man/man1/rsync.1.gz
mkdir -p $PKG/usr/man/man5
cat rsyncd.conf.5 | gzip -9c > $PKG/usr/man/man5/rsyncd.conf.5.gz
mkdir -p $PKG/usr/doc/rsync-$VERSION
cp -a README NEWS COPYING tech_report.tex $PKG/usr/doc/rsync-$VERSION
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

# Build the package:
cd $PKG
makepkg -l y -c n $TMP/rsync-$VERSION-$ARCH-$BUILD.tgz

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/rsync-$VERSION
  rm -rf $PKG
fi
