#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-inetd

VERSION=1.79s
ARCH=i386
BUILD=1

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_inetd.tar.gz

echo "+====================+"
echo "| inetd-OpenBSD-1.79 |"
echo "+====================+"
cd $TMP
tar xzvf $CWD/inetd-OpenBSD-1.79.tar.gz
cd inetd
zcat $CWD/inetd-OpenBSD-1.79.diff.gz | patch -p1 --backup --suffix=.orig --verbose -E
make
strip inetd
cat inetd > $PKG/usr/sbin/inetd
cat inetd.8 | gzip -9c > $PKG/usr/man/man8/inetd.8.gz
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

# Build the package:
cd $PKG
echo "n" | makepkg $TMP/inetd-$VERSION-$ARCH-$BUILD.tgz

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
 rm -rf $TMP/inetd
 rm -rf $PKG
fi
