#!/bin/sh
#item   ####description                                      ###on off ###
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
cat /dev/null > $TMP/SeTnewtag
dialog --title "SELECTING PACKAGES FROM SERIES T (teTeX)" \
       --checklist "Use this menu to select the packages you \
wish to install for series T (The teTeX distribution of TeX). Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to \
toggle packages on or off. RECOMMENDED and REQUIRED packages have \
been preselected. REQUIRED packages have also been marked with a [*]. \
Press ENTER when you are \
done." 16 70 4 \
"tetex" "teTeX base package *" "on" \
"tetex-doc" "teTeX documentation" "on" \
"transfig" "transfig (used by xfig)" "off" \
"xfig" "drawing tool for LaTeX" "off" \
2> $TMP/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f $TMP/SeTpkgs
 > $TMP/SeTnewtag
 for pkg in tetex tetex-doc transfig xfig ; do
  echo "$pkg: SKP" >> $TMP/SeTnewtag
 done
 exit
fi
cat /dev/null > $TMP/SeTnewtag
for PACKAGE in tetex tetex-doc transfig xfig ; do
 if fgrep \"$PACKAGE\" $TMP/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> $TMP/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> $TMP/SeTnewtag
 fi
done
rm -f $TMP/SeTpkgs
