#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-findutils

VERSION=4.1.7
ARCH=i386
BUILD=1

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_findutils.tar.gz

echo "+===============+"
echo "| findutils-$VERSION |"
echo "+===============+"
cd $TMP
tar xzvf $CWD/findutils-$VERSION.tar.gz
cd findutils-$VERSION
CFLAGS=-O2 ./configure --prefix=/usr
make
strip find/find xargs/xargs
cat find/find > $PKG/usr/bin/find
cat xargs/xargs > $PKG/usr/bin/xargs
for page in xargs/xargs.1 find/find.1 ; do
  cat $page | gzip -9c > $PKG/usr/man/man1/`basename $page`.gz
done
mkdir -p $PKG/usr/info
cat doc/find.info | gzip -9c > $PKG/usr/info/find.info.gz
cat doc/find.info-1 | gzip -9c > $PKG/usr/info/find.info-1.gz
cat doc/find.info-2 | gzip -9c > $PKG/usr/info/find.info-2.gz
cd po
for file in *.gmo ; do
  mkdir -p $PKG/usr/share/locale/`basename $file .gmo`/LC_MESSAGES
  cat $file > $PKG/usr/share/locale/`basename $file .gmo`/LC_MESSAGES/findutils.mo
done
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

# Build the package:
cd $PKG
makepkg -l y -c n $TMP/findutils-$VERSION-$ARCH-$BUILD.tgz

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/findutils-$VERSION
  rm -rf $PKG
fi
