#!/bin/sh
#item   ####description                                      ###on off ###
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
cat /dev/null > $TMP/SeTnewtag
dialog --title "SELECTING PACKAGES FROM SERIES N (NETWORK/NEWS/MAIL/UUCP)" \
       --checklist "Please select the packages you wish to install \
from series N. Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to select \
the packages you wish to install. Recommended packages have \
already been selected for you, but you may unselect them if you wish. \
Press ENTER when you are \
done." 22 70 11 \
"apache" "Apache WWW (HTTP) server" "on" \
"autofs" "Linux automounter" "on" \
"bind" "Berkeley Internet Name Domain server" "on" \
"bitchx" "BitchX Internet Relay Chat (IRC) client" "on" \
"bootp" "Internet Bootstrap Protocol server" "off" \
"curl" "Command-line URL transfer utility" "off" \
"dhcpcd" "DHCP client daemon" "on" \
"dhcp" "DHCP server (and client) utilities" "on" \
"elm" "Menu-driven user mail program" "off" \
"epic4" "EPIC4 Internet Relay Chat (IRC) client" "on" \
"fetchmail" "Fetch mail from POP/IMAP/ETRN servers" "on" \
"gnupg" "GNU Privacy Guard public key encryption" "on" \
"htdig" "Indexing and search engine" "off" \
"imapd" "ipop3d/imapd remote mail access daemons" "off" \
"inetd" "Internet super server daemon" "on" \
"inn" "InterNetNews news transport system" "on" \
"ipchains" "Firewall configuration utility for 2.2" "off" \
"iptables" "Firewall configuration utility for 2.4" "on" \
"iptraf" "Network monitoring program" "on" \
"lftp" "Shell-like FTP and HTTP transfer program" "on" \
"links" "Text-based WWW browser (with frames)" "on" \
"lynx" "Classic text-based WWW browser" "on" \
"nail" "A simple user mail program" "on" \
"metamail" "Metamail multimedia mail extensions" "on" \
"mod_ssl" "OpenSSL-based SSL security for Apache" "off" \
"mutt" "The Mutt E-Mail Client" "on" \
"nc" "Netcat network utility" "off" \
"ncftp" "NcFTP file transfer utilities" "on" \
"netatalk" "Print/file server for Apple Macs" "off" \
"netpipes" "Network pipe utilities" "off" \
"netwatch" "Another network monitoring program" "on" \
"nfs-utils" "Network File System daemons" "off" \
"nmap" "Network scanning utility" "off" \
"nn" "The NN news reader" "off" \
"ntp" "Network Time Protocol" "off" \
"openssh" "OpenSSH Secure Shell" "on" \
"openssl" "OpenSSL Secure Sockets Layer toolkit" "on" \
"php" "PHP scripting language for Apache" "off" \
"pidentd" "TCP/IP IDENT protocol server" "on" \
"pine" "Pine menu-driven mail program" "on" \
"popa3d" "Post Office Protocol v. 3 (POP3) server" "on" \
"portmap" "Manages NFS and other RPC connections" "on" \
"ppp" "Point-to-point protocol" "on" \
"procmail" "Mail delivery/filtering utility" "on" \
"proftpd" "The Professional FTP (file transfer) daemon" "on" \
"rdist" "Remote file distribution utility" "off" \
"rp-pppoe" "Connect to ADSL ISPs that use PPPoE" "on" \
"rsync" "Enhanced replacement for rcp" "off" \
"samba" "SMB print/file server for Windows LANs" "off" \
"sendmail" "The sendmail mail transport agent" "on" \
"sendmail-cf" "Extra configuration files for sendmail" "off" \
"tcpdump" "Tool for dumping network packets" "on" \
"tcpip" "Basic TCP/IP network programs and daemons" "on" \
"tin" "The 'tin' news reader" "on" \
"traceroute" "Packet tracing utility" "on" \
"trn" "A threaded news reader" "on" \
"uucp" "Taylor UUCP with HDB && Taylor configs" "off" \
"wget" "WWW/FTP retrieval tool" "on" \
"wireless-tools" "Tools for wireless networking" "off" \
"yptools" "NIS servers and clients" "off" \
"ytalk" "Multi-user talk program" "on" \
2> $TMP/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f $TMP/SeTpkgs
 > $TMP/SeTnewtag
 for pkg in \
  apache autofs bind bitchx bootp curl dhcp dhcpcd elm epic4 fetchmail gnupg htdig imapd inetd inn ipchains iptables iptraf lftp links lynx metamail mod_ssl mutt nail nc ncftp netatalk netpipes netwatch nfs-utils nmap nn ntp openssh openssl php pidentd pine popa3d portmap ppp procmail proftpd rdist rp-pppoe rsync samba sendmail sendmail-cf tcpdump tcpip tin traceroute trn uucp wget wireless-tools yptools ytalk \
  ; do
  echo "$pkg: SKP" >> $TMP/SeTnewtag
 done
 exit
fi
cat /dev/null > $TMP/SeTnewtag
for PACKAGE in \
  apache autofs bind bitchx bootp curl dhcp dhcpcd elm epic4 fetchmail gnupg htdig imapd inetd inn ipchains iptables iptraf lftp links lynx metamail mod_ssl mutt nail nc ncftp netatalk netpipes netwatch nfs-utils nmap nn ntp openssh openssl php pidentd pine popa3d portmap ppp procmail proftpd rdist rp-pppoe rsync samba sendmail sendmail-cf tcpdump tcpip tin traceroute trn uucp wget wireless-tools yptools ytalk \
 ; do
 if fgrep \"$PACKAGE\" $TMP/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> $TMP/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> $TMP/SeTnewtag
 fi
done
rm -f $TMP/SeTpkgs
