#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-nmap

VERSION=3.00
ARCH=i386
BUILD=1

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

echo "+===============+"
echo "| nmap-$VERSION |"
echo "+===============+"
cd $TMP
tar xzvf $CWD/nmap-$VERSION.tar.gz
cd nmap-$VERSION
CFLAGS="-O2 -march=i386 -mcpu=i686" ./configure --prefix=/usr i386-slackware-linux
make
make prefix=$PKG/usr install
zcat $CWD/nmapfe.desktop.gz > $PKG/usr/share/gnome/apps/Utilities/nmapfe.desktop
strip $PKG/usr/bin/*
chown -R root.bin $PKG/usr/bin
gzip -9 $PKG/usr/man/man1/*
#mkdir -p $PKG/opt/gnome/share
#mv $PKG/usr/share/gnome $PKG/opt/gnome/share
mkdir -p $PKG/usr/doc/nmap-$VERSION
cp -a \
  CHANGELOG COPYING HACKING INSTALL \
  $PKG/usr/doc/nmap-$VERSION
( cd docs
  mkdir -p $PKG/usr/man/it/man1
  cat nmap_italian.1 | gzip -9c > $PKG/usr/man/it/man1/nmap.1.gz
  mkdir -p $PKG/usr/man/lt/man1
  cat nmap_lithuanian.1 | gzip -9c > $PKG/usr/man/lt/man1/nmap.1.gz
  mkdir -p $PKG/usr/man/pt/man1
  cat nmap_portuguese.1 | gzip -9c > $PKG/usr/man/pt/man1/nmap.1.gz
  mkdir -p $PKG/usr/man/es/man1
  cat nmap_spanish.1 | gzip -9c > $PKG/usr/man/es/man1/nmap.1.gz
  cp -a \
    nmap-fingerprinting-article.txt nmap.deprecated.txt nmap.usage.txt nmap_doc.html \
    $PKG/usr/doc/nmap-$VERSION )
chmod 644 $PKG/usr/doc/nmap-$VERSION/*
chown -R root.root $PKG/usr/doc/nmap-$VERSION
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

# Build the package:
cd $PKG
makepkg -l y -c n $TMP/nmap-$VERSION-$ARCH-$BUILD.tgz

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/nmap-$VERSION
  rm -rf $PKG
fi
