#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi

PKG=$TMP/package-ytalk

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_ytalk.tar.gz

echo "+=============+"
echo "| ytalk-3.1.1 |"
echo "+=============+"
cd $TMP
tar xzvf $CWD/ytalk-3.1.1.tar.gz
cd ytalk-3.1.1
mkdir -p $PKG/usr/doc/ytalk-3.1.1
cp -a BUGS ChangeLog INSTALL README README.old ytalk-3.1.1.lsm $PKG/usr/doc/ytalk-3.1.1
chmod 644 $PKG/usr/doc/ytalk-3.1.1/*
chown root.root $PKG/usr/doc/ytalk-3.1.1/*
./configure --prefix=/usr \
            --sysconfdir=/etc \
            --with-x=no \
            i386-slackware-linux
make
strip ytalk
cat ytalk > $PKG/usr/bin/ytalk
cat ytalk.1 | gzip -9c > $PKG/usr/man/man1/ytalk.1.gz
mkdir -p $PKG/etc
cat ytalkrc > $PKG/etc/ytalkrc
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

# Build the package:
cd $PKG
makepkg -l y -c n $TMP/ytalk-3.1.1-i386-1.tgz

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
 rm -rf $TMP/ytalk-3.1.1
 rm -rf $PKG
fi
