#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-gnu-pop3d

VERSION=0.9.8
ARCH=i386
BUILD=1

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

echo "+=================+"
echo "| gnu-pop3d-$VERSION |"
echo "+=================+"
cd $TMP
tar xzvf $CWD/gnu-pop3d-$VERSION.tar.gz
cd gnu-pop3d-$VERSION
./configure --prefix=/usr i386-slackware-linux
make
strip gnu-pop3d
mkdir -p $PKG/usr/sbin
cat gnu-pop3d > $PKG/usr/sbin/gnu-pop3d
chmod 755 $PKG/usr/sbin/gnu-pop3d
chown -R root.bin $PKG/usr/sbin
mkdir -p $PKG/usr/man/man8
cat gnu-pop3d.8 | gzip -9c > $PKG/usr/man/man8/gnu-pop3d.8.gz
mkdir -p $PKG/usr/doc/gnu-pop3d-$VERSION
cat gnu-pop3d.init > $PKG/usr/doc/gnu-pop3d-$VERSION/gnu-pop3d.init
cp -a AUTHORS INSTALL IRONY README README.rfc RFC*.txt TODO $PKG/usr/doc/gnu-pop3d-$VERSION
chown -R root.root $PKG/usr/doc/gnu-pop3d-$VERSION
find $PKG/usr/doc/gnu-pop3d-$VERSION -type f -exec chmod 644 {} \;
find $PKG/usr/doc/gnu-pop3d-$VERSION -type d -exec chmod 755 {} \;
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

# Build the package:
cd $PKG
echo "n" | makepkg $TMP/gnu-pop3d-$VERSION-$ARCH-$BUILD.tgz

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/gnu-pop3d-$VERSION
  rm -rf $TMP/$dir
  rm -rf $PKG
fi
